CREATE TABLE IF NOT EXISTS categories (
                                          category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          name VARCHAR(255) NOT NULL,
                                          CONSTRAINT pk_category PRIMARY KEY (category_id),
                                          CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
                                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        name VARCHAR(255) NOT NULL,
                                        email VARCHAR(512) NOT NULL,
                                        CONSTRAINT pk_user PRIMARY KEY (user_id),
                                        CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
                                         location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         latitude FLOAT NOT NULL,
                                         longitude FLOAT NOT NULL,
                                         CONSTRAINT pk_location PRIMARY KEY (location_id)
);


