CREATE TABLE IF NOT EXISTS categories (
      category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      name VARCHAR(255) NOT NULL,
      CONSTRAINT pk_category PRIMARY KEY (category_id),
      CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(512) NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY (user_id),
        CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
     location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     lat FLOAT NOT NULL,
     lon FLOAT NOT NULL,
     CONSTRAINT pk_location PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events (
     event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     title VARCHAR(120) NOT NULL,
     annotation VARCHAR(2000) NOT NULL,
     description VARCHAR(7000),
     event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     participant_limit BIGINT,
     paid BOOLEAN NOT NULL,
     request_moderation BOOLEAN,
     confirmed_requests BIGINT,
     created_on TIMESTAMP WITHOUT TIME ZONE,
     published_on TIMESTAMP WITHOUT TIME ZONE,
     views BIGINT,
     location_id BIGINT,
     category_id BIGINT NOT NULL,
     initiator_id BIGINT NOT NULL,
     state VARCHAR(50),
     CONSTRAINT pk_item PRIMARY KEY (event_id),
     CONSTRAINT FK_EVENT_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (location_id),
     CONSTRAINT FK_EVENT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (category_id),
     CONSTRAINT FK_EVENT_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (user_id),
     CONSTRAINT UQ_INITIATOR_EVENT_NAME UNIQUE(initiator_id, title)
);

CREATE TABLE IF NOT EXISTS compilations (
      compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      title VARCHAR(255) NOT NULL,
      pinned BOOLEAN,
      CONSTRAINT pk_compilation PRIMARY KEY (compilation_id),
      CONSTRAINT UQ_COMPILATION_TITLE UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL,
    event_id      BIGINT NOT NULL,
    CONSTRAINT FILM_GENRES_PK
        PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT COMPILATIONS_EVENTS_COMPILATION_ID_FK
        FOREIGN KEY (compilation_id) REFERENCES compilations,
    CONSTRAINT COMPILATIONS_EVENTS_EVENT_ID_FK
        FOREIGN KEY (event_id) REFERENCES events
);
