version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_server

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_server
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ewm-service
    image: ewm_main_service_image
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin